### ISSUE TITLE
[Feature] Save the progress in localStorage

### ISSUE THREAD

**Issue by rahuldahal** [aabishkaryal/nepal-districts#3]
**Problem**
Currently, the progress data gets lost once the user refreshes the page

**Proposed Feature**
Store the user's progress in the `localStorage` and let them continue the game if the browser gets refreshed

**Comment by ashiishme** [comment]
+1

**Comment by TheBinitGhimire** [comment]
Possibly this can be closed now, since #12 has been merged.
